create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, visited int4, seller_id int8, primary key (id))
create table tb_sellers (id int8 generated by default as identity, name varchar(255), primary key (id))
alter table if exists tb_sales add constraint FKp0nn0oixeiw2fq3jivj6vnsu foreign key (seller_id) references tb_sellers
create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, visited int4, seller_id int8, primary key (id))
create table tb_sellers (id int8 generated by default as identity, name varchar(255), primary key (id))
alter table if exists tb_sales add constraint FKp0nn0oixeiw2fq3jivj6vnsu foreign key (seller_id) references tb_sellers
create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, visited int4, seller_id int8, primary key (id));
create table tb_sellers (id int8 generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_sales add constraint FKp0nn0oixeiw2fq3jivj6vnsu foreign key (seller_id) references tb_sellers;
/*
dados do banco Heroku
postgres://

pbdirumhymxfxm
:
6520b246f00dbffdb35287ed3808838c5b8351c801dbf2dec53bba9698a8f37e
@
ec2-54-152-185-191.compute-1.amazonaws.com
:
5432
/d1jnkm1soi7kfp
*/